# Generated by Django 3.1.2 on 2020-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('contactno', models.IntegerField()),
                ('institute', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('internshipdomain', models.CharField(max_length=200, null=True)),
                ('duration', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
                ('skills', models.TextField()),
                ('experience', models.TextField(default='')),
            ],
        ),
    ]
